_BASE_: referring_miami2025.yaml

MODEL:
  META_ARCHITECTURE: "LQMFormer"

LQM:
  DQM:
    ENABLE: True
    TOP_P: 0.2
    NQ: 100
    LOSS_WEIGHT: 1.0
    SCORE_DIM: 256

OUTPUT_DIR: "outputs/miami2025_lqm"
